### ISSUE TITLE
Some guidance on getting this working

### ISSUE THREAD

**Issue by Analect** [dgonzalez/seneca-mesh-kubernetes#1]
@paolochiodi @dgonzalez 
Thanks for assembling this demo.  I have been trying to get this basic demo working in a 1.5.2 cluster on GKE, ahead of trying to replicate it for my own app, but without success.

There are no manifest files posted in here, so I assembled a fairly basic `docker-compose.yml` ...
```
version: '2'
services:
  seneca-base:
    image: myregistry/seneca/seneca-base:0.1
    ports:
      - "39000:39000"
  seneca-act:
    image: myregistry/seneca/seneca-act:0.1
    ports:
      - "3000:3000"
    depends_on:
      - base
```
... and then used `kompose --file docker-compose.yml convert --chart` go generate a helm chart.

The generated manifest files combined together look like this.  I ended up having to add `app: seneca-act` and `app: seneca-base` labels manually.

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: seneca-base
    app: seneca-base
  name: seneca-base
spec:
  ports:
  - name: "39000"
    port: 39000
    protocol: TCP
    targetPort: 39000
  selector:
    service: seneca-base
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: seneca-act
    app: seneca-act
  name: seneca-act
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    service: seneca-act
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: seneca-base
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: seneca-base
    spec:
      containers:
      - image: myregistry/seneca/seneca-base:0.1
        name: seneca-base
        ports:
        - containerPort: 39000
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: seneca-act
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: seneca-act
    spec:
      containers:
      - image: myregistry/seneca/seneca-act:0.1
        name: seneca-act
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
```
Are there any glaring mistakes in there?  The reason being that on deployment, the services are terminating immediately.  I'm wondering if perhaps the kubernetes API that the plugin references may have changed.

![image](https://cloud.githubusercontent.com/assets/4063815/23138396/2eaa22b2-f79f-11e6-8197-025bfee58740.png)

Also, I notice that port `39000` is being used here for base, as against the default `39999`.  Perhaps that's a factor?

In layman's terms, how is seneca-mesh leverage networking within kubernetes to function?  Presumably it's possible to scale up certain instances of services and it just works.  Thanks for any guidance you might have to get this to work.
